default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "1787" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 3306 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "inspira_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "inspira_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "inspira_production" } %>